// <auto-generated>
// Code generated by LUISGen .\FlightBooking.json -cs Luis.FlightBooking -o .
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;

namespace CodeFestBot.CognitiveModels
{
	public partial class TweetsDetail : IRecognizerConvert
	{
		public enum Intent
		{
			Greetings,
			None,
			Ponencias,
			TweetFunniest,
			TweetSaddest,
			NumberOfTweets,
			TopNFunniestTweets
		};
	

		public class _Entities
		{
			[JsonProperty("$instance")]
			public _Instance instance { get; set; }
			public int[] number { get; set; }
		}

		public class _Instance
		{
			public Number[] number { get; set; }
		}

		public class Number
		{
			public int startIndex { get; set; }
			public int endIndex { get; set; }
			public string text { get; set; }
			public string type { get; set; }
		}

		public Dictionary<Intent, IntentScore> Intents;
		public string AlteredText { get; set; }
		public _Entities Entities { get; set; }			
		public string Properties { get; set; }
		public string Text { get; set; }


		//public string Text;
		//public string AlteredText;
		//public Dictionary<Intent, IntentScore> Intents;

		//public int Top;

		//public class _Entities
		//{
		//	public int Top;

		//	// Built-in entities
		//	// public DateTimeSpec[] datetime;

		//	// Composites
		//	//public class _InstanceFrom
		//	//{
		//	//	public InstanceData[] Top;
		//	//}
		//	//public class FromClass
		//	//{
		//	//	public int Top;
		//	//	[JsonProperty("$instance")]
		//	//	public _InstanceFrom _instance;
		//	//}
		//	//public FromClass[] From;

		//	//public class _InstanceTo
		//	//{
		//	//	public InstanceData[] Top;
		//	//}
		//	//public class ToClass
		//	//{
		//	//	public int Top;
		//	//	[JsonProperty("$instance")]
		//	//	public _InstanceTo _instance;
		//	//}
		//	//public ToClass[] To;

		//	// Instance
		//	public class _Instance
		//	{
		//		public InstanceData[] Top;
		//	}
		//	[JsonProperty("$instance")]
		//	public _Instance _instance;
		//}

		// public _Entities Entities;

		//[JsonExtensionData(ReadData = true, WriteData = true)]
		//public IDictionary<string, object> Properties { get; set; }

		public void Convert(dynamic result)
		{
			var app = JsonConvert.DeserializeObject<TweetsDetail>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
			Text = app.Text;
			AlteredText = app.AlteredText;
			Intents = app.Intents;
			Entities = app.Entities;
			Properties = app.Properties;
		}

		public (Intent intent, double score) TopIntent()
		{
			Intent maxIntent = Intent.None;
			var max = 0.0;
			foreach (var entry in Intents)
			{
				if (entry.Value.Score > max)
				{
					maxIntent = entry.Key;
					max = entry.Value.Score.Value;
				}
			}
			return (maxIntent, max);
		}
	}
}
